on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install pydantic
        run: pip install pydantic
      - name: execute scripts
        env:
          G_CONTEXT: ${{ toJSON(github) }}
          TOKEN: ${{ secrets.TEST_TOKEN }}
        run: python3 .github/actions/conf.py